// Genera server/AegiFitness.Api/Data/Seed/SeedCatalog.cs desde los catálogos legacy.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const exercises = JSON.parse(readFileSync(join(root, "client/src/data/exercises.json"), "utf8"));
const meals = JSON.parse(readFileSync(join(root, "client/src/data/meals.json"), "utf8"));

const MUSCLE = { "Pecho": "Chest", "Espalda": "Back", "Piernas": "Legs", "Hombros": "Shoulders", "Bíceps": "Biceps", "Tríceps": "Triceps", "Abdomen": "Core" };
const TYPE = { "Gimnasio": "Gym", "Calistenia": "Calisthenics" };
const OBJ = { "Aumento": "Bulk", "Definición": "Cut", "Ambos": "Both" };
const MEAL = { "Desayuno": "Breakfast", "Almuerzo": "Lunch", "Cena": "Dinner", "Bebida": "Snack" };

const cs = (s) => `"${String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, "\\n")}"`;
const cleanName = (s) => String(s).replace(/\s*\((?:Fase de|Para)[^)]*\)\s*/g, "").trim();

function difficultyOf(e) {
  const n = e.name.toLowerCase();
  if (/peso muerto|sentadilla|press militar|dominada|fondos|muscle.?up|front lever|plancha|handstand/.test(n)) return 3;
  if (/press|remo|jal[oó]n|curl|elevaci|extensi|flexiones|zancadas|hip thrust/.test(n)) return 2;
  return 1;
}
function equipmentOf(e) {
  const n = `${e.name} ${e.instructions}`.toLowerCase();
  if (e.type === "Calistenia") {
    if (/dominada|barra fija/.test(n)) return "Barra de dominadas";
    if (/fondos|paralelas/.test(n)) return "Barras paralelas";
    if (/anillas/.test(n)) return "Anillas";
    return "Peso corporal";
  }
  if (/barra(?! de dominadas)/.test(n)) return "Barra olímpica";
  if (/mancuerna/.test(n)) return "Mancuernas";
  if (/polea|cable/.test(n)) return "Polea";
  if (/m[aá]quina|smith|prensa/.test(n)) return "Máquina";
  if (/kettlebell|pesa rusa/.test(n)) return "Kettlebell";
  return "Barra y mancuernas";
}

const exOut = exercises.map((e) => {
  return `new(${cs(cleanName(e.name))}, "${MUSCLE[e.muscleGroup]}", "${TYPE[e.type]}", "${OBJ[e.objective]}", ${difficultyOf(e)}, ${cs(equipmentOf(e))}, ${cs(e.description)}, ${cs(e.instructions)}, ${cs(e.target)}, ${cs(e.effect)})`;
});

const meOut = meals.map((m) => {
  const fat = Math.max(0, Math.round((m.calories - m.protein * 4 - m.carbs * 4) / 9));
  const ing = (m.recipe?.ingredients ?? []).map(cs).join(", ");
  const stp = (m.recipe?.steps ?? []).map(cs).join(", ");
  return `new(${cs(cleanName(m.name))}, "${MEAL[m.type]}", "${OBJ[m.objective]}", ${m.calories}, ${m.protein}, ${m.carbs}, ${fat}, ${m.sugars ?? 0}, ${cs(m.recipe?.portions ?? "1 porción")}, new[]{ ${ing} }, new[]{ ${stp} }, ${cs(m.description)})`;
});

const file = `// <auto-generated> Generado por client/scripts/gen-seed.mjs — no editar a mano. </auto-generated>
namespace AegiFitness.Api.Data.Seed;

public static partial class SeedCatalog
{
    public static readonly ExerciseSeed[] Exercises = new ExerciseSeed[]
    {
        ${exOut.join(",\n        ")}
    };

    public static readonly FoodSeed[] Foods = new FoodSeed[]
    {
        ${meOut.join(",\n        ")}
    };
}
`;

const outDir = join(root, "server/AegiFitness.Api/Data/Seed");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "SeedCatalog.cs"), file, "utf8");
console.log(`OK: ${exOut.length} ejercicios, ${meOut.length} comidas -> ${outDir}`);
