import { useCallback, useEffect, useMemo, useState } from "react";
import { analyticsApi } from "../api/resources";
import { Button, Card, EmptyState, ErrorState, ExerciseGuideModal, Loading, Modal, SegmentedControl } from "../components/ui";
import { Badge, BarChart, LineChart, RingProgress, StatCard } from "../components/ui/charts";
import { useAsync } from "../hooks/useAsync";
import type { ExerciseDto, ExerciseHistoryDto, FitnessCalendarDayDto, PersonalRecordDto } from "../types/api";
import { addDays, muscleGroupName, today } from "../utils/format";

type View = "calendar" | "exercises" | "records" | "consistency";
type ExerciseMetric = "volumeKg" | "maxWeightKg" | "estimatedOneRepMax";
const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const parseDate = (value: string) => { const [year = 2000, month = 1, day = 1] = value.split("-").map(Number); return new Date(year, month - 1, day); };
const dateLabel = (value: string) => new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short", year: "numeric" }).format(parseDate(value));
const formatNumber = (value: number, digits = 0) => new Intl.NumberFormat("es-MX", { maximumFractionDigits: digits, notation: value >= 10000 ? "compact" : "standard" }).format(value);

export default function InsightsPage() {
  const [view, setView] = useState<View>("calendar");
  const [month, setMonth] = useState(() => { const date = new Date(); return new Date(date.getFullYear(), date.getMonth(), 1); });
  const [calendar, setCalendar] = useState<FitnessCalendarDayDto[]>([]);
  const [calendarLoading, setCalendarLoading] = useState(true);
  const [selectedDay, setSelectedDay] = useState<FitnessCalendarDayDto | null>(null);
  const { data, loading, error, run } = useAsync<{ exercises: ExerciseHistoryDto[]; records: PersonalRecordDto[]; adherence: Awaited<ReturnType<typeof analyticsApi.adherence>> }>();
  const load = useCallback(() => void run(Promise.all([analyticsApi.exercises(addDays(today(), -365), today()), analyticsApi.personalRecords(), analyticsApi.adherence(today())]).then(([exercises, records, adherence]) => ({ exercises, records, adherence }))), [run]);
  useEffect(load, [load]);
  const range = useMemo(() => {
    const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0);
    const start = new Date(first); start.setDate(first.getDate() - first.getDay());
    const end = new Date(last); end.setDate(last.getDate() + (6 - last.getDay()));
    return { start: iso(start), end: iso(end) };
  }, [month]);
  useEffect(() => { let active = true; setCalendarLoading(true); analyticsApi.calendar(range.start, range.end).then((result) => { if (active) setCalendar(result); }).finally(() => { if (active) setCalendarLoading(false); }); return () => { active = false; }; }, [range]);

  if (loading && !data) return <Loading message="Analizando tu progreso" />;
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!data) return <EmptyState icon="monitoring" title="Todavía no hay analítica" />;

  return <div className="page insights-page">
    <div className="hero insights-hero"><div><div className="hero__label"><span className="icon">monitoring</span><span>Análisis</span></div><h1 className="hero__title">Tu progreso, con contexto</h1><p className="hero__subtitle">Descubrí patrones, récords y consistencia usando lo que realmente registraste.</p></div><div className="insights-hero__score"><RingProgress value={data.adherence.overall30d} max={100} size={94} stroke={8}><strong>{data.adherence.overall30d}%</strong></RingProgress><span>Consistencia<br />30 días</span></div></div>
    <div className="mb-4"><SegmentedControl block value={view} onChange={setView} options={[{ value: "calendar", label: "Calendario" }, { value: "exercises", label: "Ejercicios" }, { value: "records", label: "Récords" }, { value: "consistency", label: "Consistencia" }]} /></div>
    {view === "calendar" && <FitnessCalendar month={month} days={calendar} loading={calendarLoading} onMonth={setMonth} onDay={setSelectedDay} />}
    {view === "exercises" && <ExerciseHistory items={data.exercises} />}
    {view === "records" && <PersonalRecords items={data.records} />}
    {view === "consistency" && <Consistency data={data.adherence} />}
    <DayDetail day={selectedDay} onClose={() => setSelectedDay(null)} />
  </div>;
}

function FitnessCalendar({ month, days, loading, onMonth, onDay }: { month: Date; days: FitnessCalendarDayDto[]; loading: boolean; onMonth: (date: Date) => void; onDay: (day: FitnessCalendarDayDto) => void }) {
  const monthName = new Intl.DateTimeFormat("es-MX", { month: "long", year: "numeric" }).format(month);
  const currentMonthDays = days.filter((day) => day.isTracked && parseDate(day.date).getMonth() === month.getMonth() && day.date <= today());
  const activeDays = currentMonthDays.filter((day) => day.hasWorkout || day.hasNutrition || day.hasMeasurement).length;
  const average = currentMonthDays.length ? Math.round(currentMonthDays.reduce((sum, day) => sum + day.overallAdherence, 0) / currentMonthDays.length) : 0;
  return <section className="fitness-calendar-section"><div className="calendar-toolbar"><div><span className="text-muted">Calendario fitness</span><h2>{monthName}</h2></div><div><button onClick={() => onMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Mes anterior"><span className="icon">chevron_left</span></button><button onClick={() => onMonth(new Date())}>Hoy</button><button onClick={() => onMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Mes siguiente" disabled={month.getFullYear() === new Date().getFullYear() && month.getMonth() >= new Date().getMonth()}><span className="icon">chevron_right</span></button></div></div><div className="calendar-summary"><span><strong>{activeDays}</strong> días activos</span><span><strong>{average}%</strong> adherencia media</span><span><i className="calendar-dot calendar-dot--workout" />Entreno</span><span><i className="calendar-dot calendar-dot--nutrition" />Nutrición</span><span><i className="calendar-dot calendar-dot--body" />Cuerpo</span></div>{loading ? <Loading message="Cargando calendario" /> : <div className="fitness-calendar"><div className="fitness-calendar__weekdays">{["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"].map((day) => <span key={day}>{day}</span>)}</div><div className="fitness-calendar__grid">{days.map((day) => { const date = parseDate(day.date); const outside = date.getMonth() !== month.getMonth(); const future = day.date > today(); const level = day.overallAdherence >= 90 ? "perfect" : day.overallAdherence >= 70 ? "good" : day.overallAdherence > 0 ? "low" : "empty"; return <button key={day.date} type="button" className={`fitness-day fitness-day--${level} ${outside ? "fitness-day--outside" : ""} ${day.date === today() ? "fitness-day--today" : ""}`} disabled={future || !day.isTracked} onClick={() => onDay(day)} aria-label={`${dateLabel(day.date)}, adherencia ${day.overallAdherence}%`}><span className="fitness-day__number">{date.getDate()}</span>{day.personalRecords > 0 && <span className="fitness-day__pr" title={`${day.personalRecords} récords`}>PR</span>}<div className="fitness-day__score">{day.overallAdherence > 0 ? `${day.overallAdherence}%` : day.isRestDay && day.nutritionAdherence == null ? <span className="icon">bedtime</span> : day.nutritionAdherence != null ? "0%" : ""}</div><div className="fitness-day__dots">{day.hasWorkout && <i className="calendar-dot calendar-dot--workout" />}{day.hasNutrition && <i className="calendar-dot calendar-dot--nutrition" />}{day.hasMeasurement && <i className="calendar-dot calendar-dot--body" />}</div></button>; })}</div></div>}</section>;
}

function DayDetail({ day, onClose }: { day: FitnessCalendarDayDto | null; onClose: () => void }) {
  if (!day) return null;
  return <Modal open onClose={onClose} title={dateLabel(day.date)}><div className="calendar-day-detail"><div className="calendar-day-detail__hero"><RingProgress value={day.overallAdherence} max={100} size={112}><strong>{day.overallAdherence}%</strong></RingProgress><div><h3>{day.overallAdherence >= 90 ? "Día excelente" : day.overallAdherence >= 70 ? "Buen cumplimiento" : day.overallAdherence > 0 ? "Seguís sumando" : "Sin registros"}</h3><p>{day.personalRecords ? `${day.personalRecords} nuevo${day.personalRecords > 1 ? "s" : ""} récord${day.personalRecords > 1 ? "s" : ""} personal${day.personalRecords > 1 ? "es" : ""}` : day.isRestDay ? "Descanso programado respetado" : "Revisá qué parte del plan faltó completar"}</p></div></div><ScoreRow icon="fitness_center" label={day.isRestDay && !day.hasWorkout ? "Entrenamiento · descanso" : `Entrenamiento · ${day.completedSets}/${day.plannedSets} series`} value={day.trainingAdherence} /><ScoreRow icon="restaurant" label={`Nutrición · ${day.calories}/${day.targetCalories || "—"} kcal`} value={day.nutritionAdherence} /><div className="calendar-day-detail__stats"><span><strong>{formatNumber(day.workoutVolumeKg)}</strong>kg volumen</span><span><strong>{day.hasMeasurement ? "Sí" : "No"}</strong>control corporal</span></div></div></Modal>;
}
function ScoreRow({ icon, label, value }: { icon: string; label: string; value?: number }) { return <div className="score-row"><span className="icon">{icon}</span><div><span>{label}</span><div><i style={{ width: `${value ?? 0}%` }} /></div></div><strong>{value == null ? "—" : `${value}%`}</strong></div>; }

function ExerciseHistory({ items }: { items: ExerciseHistoryDto[] }) {
  const [search, setSearch] = useState(""); const [selectedId, setSelectedId] = useState<number | null>(items[0]?.exercise.id ?? null); const [metric, setMetric] = useState<ExerciseMetric>("volumeKg"); const [guide, setGuide] = useState<ExerciseDto | null>(null);
  const filtered = items.filter((item) => item.exercise.name.toLowerCase().includes(search.toLowerCase()) || muscleGroupName(item.exercise.muscleGroup).toLowerCase().includes(search.toLowerCase()));
  const selected = items.find((item) => item.exercise.id === selectedId) ?? filtered[0];
  if (!items.length) return <EmptyState icon="history" title="Sin historial por ejercicio" description="Tus ejercicios aparecerán después de registrar series reales." />;
  const metricLabel = metric === "volumeKg" ? "Volumen" : metric === "maxWeightKg" ? "Peso máximo" : "1RM estimado";
  return <div className="exercise-history-layout"><aside className="exercise-history-list"><div className="insights-search"><span className="icon">search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar ejercicio o músculo" /></div><div>{filtered.map((item) => <button type="button" key={item.exercise.id} className={item.exercise.id === selected?.exercise.id ? "is-active" : ""} onClick={() => setSelectedId(item.exercise.id)}><span className="exercise-history-list__icon"><span className="icon">fitness_center</span></span><span><strong>{item.exercise.name}</strong><small>{muscleGroupName(item.exercise.muscleGroup)} · {item.sessions} sesiones</small></span><span className="icon">chevron_right</span></button>)}</div></aside>{selected && <main className="exercise-history-detail"><div className="exercise-history-detail__head"><div><span className="text-muted">Última vez · {dateLabel(selected.lastPerformed)}</span><h2>{selected.exercise.name}</h2><p>{muscleGroupName(selected.exercise.muscleGroup)} · {selected.exercise.equipment}</p></div><Button variant="ghost" size="sm" onClick={() => setGuide(selected.exercise)}><span className="icon">info</span>Guía</Button></div><div className="exercise-history-kpis"><div><span>Peso máximo</span><strong>{selected.bestWeightKg ? `${selected.bestWeightKg} kg` : "—"}</strong></div><div><span>Mejores reps</span><strong>{selected.bestReps || "—"}</strong></div><div><span>1RM estimado</span><strong>{selected.bestEstimatedOneRepMax ? `${selected.bestEstimatedOneRepMax} kg` : "—"}</strong></div><div><span>Tendencia</span><strong className={selected.trendPercent >= 0 ? "is-positive" : "is-negative"}>{selected.trendPercent > 0 ? "+" : ""}{selected.trendPercent}%</strong></div></div><Card title={`Evolución · ${metricLabel}`} icon="show_chart"><select className="select exercise-metric-select" value={metric} onChange={(event) => setMetric(event.target.value as ExerciseMetric)}><option value="volumeKg">Volumen de sesión</option><option value="maxWeightKg">Peso máximo</option><option value="estimatedOneRepMax">1RM estimado</option></select>{selected.recent.length > 1 ? <LineChart height={230} data={selected.recent.map((point) => ({ label: point.date.slice(5), value: point[metric] }))} /> : <EmptyState icon="show_chart" title="Necesitás otra sesión" description="Con dos registros podremos mostrar la tendencia." />}</Card><div className="exercise-history-sessions"><div className="section-title"><span>Sesiones recientes</span></div>{[...selected.recent].reverse().slice(0, 6).map((point) => <div key={point.date}><span><strong>{dateLabel(point.date)}</strong><small>{point.completedSets} series · {point.totalReps} reps</small></span><span><strong>{formatNumber(point.volumeKg)} kg</strong><small>{point.maxWeightKg ? `Máx. ${point.maxWeightKg} kg` : "Peso corporal"}</small></span></div>)}</div></main>}<ExerciseGuideModal exercise={guide} onClose={() => setGuide(null)} /></div>;
}

function PersonalRecords({ items }: { items: PersonalRecordDto[] }) {
  const [search, setSearch] = useState(""); const [guide, setGuide] = useState<ExerciseDto | null>(null);
  const filtered = items.filter((item) => item.exercise.name.toLowerCase().includes(search.toLowerCase()) || muscleGroupName(item.exercise.muscleGroup).toLowerCase().includes(search.toLowerCase()));
  if (!items.length) return <EmptyState icon="emoji_events" title="Todavía no hay récords" description="Completá series con peso o repeticiones para establecer tus primeras marcas." />;
  return <section><div className="records-toolbar"><div><h2>Récords personales</h2><p>Mejores marcas calculadas desde tus series completadas.</p></div><div className="insights-search"><span className="icon">search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar récord" /></div></div><div className="records-grid">{filtered.map((record) => <article className="record-card" key={record.exercise.id}><div className="record-card__top"><span className="record-card__trophy"><span className="icon">trophy</span></span>{record.improvedRecently && <Badge variant="success">Nuevo · 30d</Badge>}<button onClick={() => setGuide(record.exercise)} aria-label={`Ver guía de ${record.exercise.name}`}><span className="icon">info</span></button></div><h3>{record.exercise.name}</h3><p>{muscleGroupName(record.exercise.muscleGroup)} · {record.totalSessions} sesiones</p><div className="record-card__main"><span>1RM estimado</span><strong>{record.bestEstimatedOneRepMax ? `${record.bestEstimatedOneRepMax} kg` : "—"}</strong><small>{record.bestEstimatedOneRepMaxDate ? dateLabel(record.bestEstimatedOneRepMaxDate) : "Sin carga registrada"}</small></div><div className="record-card__metrics"><span><small>Peso máximo</small><strong>{record.bestWeightKg ? `${record.bestWeightKg} kg × ${record.repsAtBestWeight}` : "—"}</strong></span><span><small>Máx. reps</small><strong>{record.bestReps || "—"}</strong></span><span><small>Mejor volumen</small><strong>{record.bestSessionVolumeKg ? `${formatNumber(record.bestSessionVolumeKg)} kg` : "—"}</strong></span></div></article>)}</div><ExerciseGuideModal exercise={guide} onClose={() => setGuide(null)} /></section>;
}

function Consistency({ data }: { data: Awaited<ReturnType<typeof analyticsApi.adherence>> }) {
  const completion = data.plannedWorkouts30d ? Math.round(data.completedWorkouts30d / data.plannedWorkouts30d * 100) : 0;
  return <section className="consistency"><div className="consistency-rings"><AdherenceRing label="Entrenamiento" value={data.training30d} hint={`${data.trainingStreak} sesiones de racha`} /><AdherenceRing label="Nutrición" value={data.nutrition30d} hint={`${data.nutritionStreak} días de racha`} /><AdherenceRing label="General" value={data.overall30d} hint={`${data.overallStreak} días de racha`} /></div><div className="grid-4 mt-4"><StatCard icon="verified" label="Días excelentes" value={data.perfectDays30d} hint="90% o más · 30 días" variant="success" /><StatCard icon="fitness_center" label="Rutinas cumplidas" value={`${data.completedWorkouts30d}/${data.plannedWorkouts30d}`} hint={`${completion}% del plan`} variant="primary" /><StatCard icon="calendar_view_week" label="Adherencia 7 días" value={`${data.overall7d}%`} hint={`Anterior: ${data.overall30d}% mensual`} variant="accent" /><StatCard icon="local_fire_department" label="Racha general" value={`${data.overallStreak} días`} hint="Descansos no la interrumpen" variant="danger" /></div><div className="grid-2 mt-4"><Card title="Tendencia de 12 semanas" icon="trending_up"><LineChart height={220} data={data.weeklyTrend.map((week) => ({ label: week.startDate.slice(5), value: week.overall }))} /></Card><Card title="Entrenamiento vs nutrición" icon="compare_arrows"><BarChart height={220} max={100} data={data.weeklyTrend.slice(-6).flatMap((week) => [{ label: `E ${week.startDate.slice(5)}`, value: week.training, color: "var(--primary)" }, { label: `N ${week.startDate.slice(5)}`, value: week.nutrition, color: "var(--success)" }])} /></Card></div><div className="adherence-explainer"><span className="icon">info</span><div><strong>Ahora la adherencia mide cumplimiento real</strong><p>Entrenamiento compara series completadas con las programadas. Nutrición evalúa calorías y macros con tolerancias saludables. Los días de descanso programados no penalizan tu racha de entrenamiento.</p></div></div></section>;
}
function AdherenceRing({ label, value, hint }: { label: string; value: number; hint: string }) { return <div className="adherence-ring-card"><RingProgress value={value} max={100} size={132} stroke={11}><div><strong>{value}%</strong><small>30 días</small></div></RingProgress><h3>{label}</h3><p>{hint}</p></div>; }
